"""초기 스키마 - BRIEF 6 데이터 모델

Revision ID: 0e27d005575b
Revises: 
Create Date: 2026-07-28 12:08:40.247309
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0e27d005575b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('a2a_url', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('UP', 'DOWN', name='nodestatus', native_enum=False), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dgx_host', sa.String(length=64), nullable=True),
    sa.Column('card', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodes_role'), ['role'], unique=True)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('ORDER_SITE', 'INQUIRY', 'MANUAL', name='ordersource', native_enum=False), nullable=False),
    sa.Column('kind', sa.Enum('NEW', 'CHANGE', 'DEFECT', 'SECURITY', name='orderkind', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('requester', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('pipeline', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('READY', 'RUNNING', 'PAUSED', 'BLOCKED', 'FAILED', 'DONE', name='cyclestatus', native_enum=False), nullable=False),
    sa.Column('current_step', sa.String(length=16), nullable=True),
    sa.Column('mode', sa.Enum('AUTO', 'MANUAL', name='cyclemode', native_enum=False), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycles_order_id'), ['order_id'], unique=False)

    op.create_table('agent_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CUSTOMIZED', name='specstatus', native_enum=False), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('diff_ref', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_specs_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_specs_role'), ['role'], unique=False)

    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('step_key', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'REJECTED', 'FAILED', 'SKIPPED', 'WAITING_HUMAN', name='stepstatus', native_enum=False), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('input_ref', sa.String(length=512), nullable=True),
    sa.Column('output_ref', sa.String(length=512), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_steps_cycle_id'), ['cycle_id'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('from_role', sa.String(length=32), nullable=False),
    sa.Column('to_role', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('dod', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_cycle_id'), ['cycle_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_cycle_id'), ['cycle_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('from_role', sa.String(length=32), nullable=False),
    sa.Column('to_role', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('REQUEST', 'RESPONSE', 'REJECT', 'MIRROR', name='messagekind', native_enum=False), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('payload_ref', sa.String(length=512), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_cycle_id'), ['cycle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_cycle_id'))

    op.drop_table('messages')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_cycle_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_cycle_id'))

    op.drop_table('tickets')
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_steps_cycle_id'))

    op.drop_table('steps')
    with op.batch_alter_table('agent_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_specs_role'))
        batch_op.drop_index(batch_op.f('ix_agent_specs_cycle_id'))

    op.drop_table('agent_specs')
    with op.batch_alter_table('cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycles_order_id'))

    op.drop_table('cycles')
    op.drop_table('orders')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodes_role'))

    op.drop_table('nodes')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
